{
 "title": "projet_final",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nombre total d'aéroports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT count(airport_id) FROM airports"
    }
   ]
  },
  {
   "title": "Nombre de pays couverts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT count(DISTINCT country) FROM airports"
    }
   ]
  },
  {
   "title": "Aéroports privés / publics",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT\r\n  CASE \r\n    WHEN is_private = true THEN 'Est privé'\r\n    WHEN is_private = false THEN 'Est public' \r\n    ELSE 'Inconnu' -- C'est une bonne pratique de gérer les valeurs NULL\r\n  END AS statut_privé,\r\n  count(*) AS count\r\nFROM airports\r\nGROUP BY statut_privé -- Assurez-vous de grouper par le nouveau nom d'alias"
    }
   ]
  },
  {
   "title": "Top 10 des Pays par Nombre d'Aéroports",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT\r\n  country,\r\n  count(airport_id) AS total_airports\r\nFROM airports\r\nGROUP BY country\r\nORDER BY total_airports DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Distribution des Altitudes",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 4 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT elevation_meters FROM airports"
    }
   ]
  },
  {
   "title": "Répartition par Catégorie d'Aéroport",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT\r\n  CASE \r\n    WHEN airport_type IN (1, 2, 3, 5, 6) THEN 'Aérodrome / Terrain'\r\n    WHEN airport_type IN (7, 8, 9) THEN 'Héliport'\r\n    WHEN airport_type = 4 THEN 'Terrain de Vol à Voile'\r\n    WHEN airport_type IN (10, 11, 19) THEN 'Point de Navigation'\r\n    WHEN airport_type IN (12, 13, 14, 15, 16, 17, 18) THEN 'Station de Navigation (Radio)'\r\n    WHEN airport_type = 20 THEN 'Phare'\r\n    ELSE 'Inconnu'\r\n  END AS categorie,\r\n  count(*) AS total\r\nFROM airports\r\nGROUP BY categorie\r\nORDER BY total DESC"
    }
   ]
  },
  {
   "title": "Localisation des aéroports",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT name, longitude, latitude FROM airports"
    },
    {
     "dataset": "mydb",
     "rawSql": "SELECT name, icao, elevation_meters, longitude, latitude FROM airports"
    }
   ]
  }
 ]
}